dev:
  restart: always
  build: .
  ports:
    - "5000:5000"
    - "8080:8080"
    - "8888:8888"
    - "2222:22"
  links:
    - mysql
    - redis
    - postgres
    - mongo
    - memcached
  volumes:
    - /Users/kikukotoda/development:/home/todakikuko/works

mysql:
  restart: always
  image: mysql
  volumes:
    - ./data/mysql:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root

postgres:
  restart: always
  image: postgres
  volumes:
    - ./data/postgresql:/var/lib/postgresql/data

redis:
  restart: always
  image: redis
  volumes:
    - ./data/redis:/data
  command: redis-server --appendonly yes

mongo:
  restart: always
  image: mongo
  volumes:
    - ./data/mongo:/data/db

memcached:
  restart: always
  image: memcached
